# Generated by Django 5.2.16 on 2026-07-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproduct',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='educationtrack',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='internationalservice',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='researchcapability',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='researchstudy',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Tartib'),
        ),
    ]
