# Generated by Django 6.0.5 on 2026-08-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_normalize_uz_apostrophe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='team_image_url',
            field=models.CharField(blank=True, max_length=512, verbose_name='Yoki rasm yo‘li/URL'),
        ),
    ]
