# Generated by Django 6.0.5 on 2026-08-06 05:35

import cms.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_homepage_i18n_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='resume',
            field=models.FileField(blank=True, help_text='PDF, DOC yoki DOCX, 5MB gacha.', null=True, upload_to='resumes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), cms.utils.validate_resume_size], verbose_name='Rezyume (PDF/DOC)'),
        ),
    ]
