# Generated by Django 6.0.5 on 2026-08-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_inquiry_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='aiproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='clinictourvideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='clinictourvideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='educationprogram',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='educationtrack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='educationtrack',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='internationalservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='internationalservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='researchcapability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='researchcapability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='researchsection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='researchsection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='researchstudy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='researchstudy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
    ]
