# Generated by Django 5.2.16 on 2026-08-06 07:13
# Hand-edited: keep existing Uzbek "experience" text by renaming the column
# instead of dropping it (Django's autodetector defaults to remove+add when
# run non-interactively, which would have discarded every doctor's value).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_alter_aiproduct_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='experience',
            new_name='experience_uz',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience_uz',
            field=models.CharField(blank=True, max_length=64, verbose_name='Tajriba (UZ)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience_en',
            field=models.CharField(blank=True, max_length=64, verbose_name='Tajriba (EN)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience_ru',
            field=models.CharField(blank=True, max_length=64, verbose_name='Tajriba (RU)'),
        ),
    ]
