# Generated by Django 6.0.5 on 2026-08-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_remove_doctor_experience_doctor_experience_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternationalService',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
