# Generated by Django 6.0.5 on 2026-08-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_delete_internationalservice_delete_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchcapability',
            name='label_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='Nom (EN)'),
        ),
        migrations.AlterField(
            model_name='researchcapability',
            name='label_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Nom (RU)'),
        ),
        migrations.AlterField(
            model_name='researchcapability',
            name='label_uz',
            field=models.CharField(max_length=128, verbose_name='Nom (UZ)'),
        ),
        migrations.AlterField(
            model_name='researchstudy',
            name='phase',
            field=models.CharField(blank=True, choices=[('I', 'I bosqich'), ('II', 'II bosqich'), ('III', 'III bosqich'), ('IV', 'IV bosqich')], max_length=32, verbose_name='Bosqich'),
        ),
        migrations.AlterField(
            model_name='researchstudy',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Ochiq (qabul davom etmoqda)'), ('closed', 'Yopiq (qabul tugagan)')], max_length=32, verbose_name='Holat'),
        ),
    ]
