# Generated by Django 6.0.5 on 2026-08-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_alter_researchcapability_label_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproduct',
            name='metric',
            field=models.CharField(blank=True, max_length=64, verbose_name='Metrika (katta raqam)'),
        ),
        migrations.AlterField(
            model_name='aiproduct',
            name='metric_label_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='Metrika izohi (EN)'),
        ),
        migrations.AlterField(
            model_name='aiproduct',
            name='metric_label_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Metrika izohi (RU)'),
        ),
        migrations.AlterField(
            model_name='aiproduct',
            name='metric_label_uz',
            field=models.CharField(blank=True, max_length=128, verbose_name='Metrika izohi (UZ)'),
        ),
        migrations.AlterField(
            model_name='aiproduct',
            name='product_key',
            field=models.CharField(blank=True, max_length=64, verbose_name='Ichki kod (dasturchi uchun)'),
        ),
        migrations.AlterField(
            model_name='aiproduct',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Sahifa manzili (URL)'),
        ),
        migrations.AlterField(
            model_name='aiproduct',
            name='tag_color',
            field=models.CharField(blank=True, default='#5B4CDB', max_length=32, verbose_name='Yorliq rangi'),
        ),
        migrations.AlterField(
            model_name='aiproduct',
            name='tag_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='Yorliq (EN)'),
        ),
        migrations.AlterField(
            model_name='aiproduct',
            name='tag_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Yorliq (RU)'),
        ),
        migrations.AlterField(
            model_name='aiproduct',
            name='tag_uz',
            field=models.CharField(blank=True, max_length=128, verbose_name='Yorliq (UZ)'),
        ),
        migrations.AlterField(
            model_name='educationtrack',
            name='icon',
            field=models.CharField(blank=True, max_length=16, verbose_name='Ikonka (emoji)'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='tagline_en',
            field=models.CharField(blank=True, max_length=512, verbose_name='Kichik sarlavha (EN)'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='tagline_ru',
            field=models.CharField(blank=True, max_length=512, verbose_name='Kichik sarlavha (RU)'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='tagline_uz',
            field=models.CharField(blank=True, max_length=512, verbose_name='Kichik sarlavha (UZ)'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Sahifa manzili (URL)'),
        ),
        migrations.AlterField(
            model_name='researchsection',
            name='label_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='Kichik yorliq (EN)'),
        ),
        migrations.AlterField(
            model_name='researchsection',
            name='label_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Kichik yorliq (RU)'),
        ),
        migrations.AlterField(
            model_name='researchsection',
            name='label_uz',
            field=models.CharField(blank=True, max_length=128, verbose_name='Kichik yorliq (UZ)'),
        ),
        migrations.AlterField(
            model_name='researchsection',
            name='sponsor_btn_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='Tugma matni (EN)'),
        ),
        migrations.AlterField(
            model_name='researchsection',
            name='sponsor_btn_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Tugma matni (RU)'),
        ),
        migrations.AlterField(
            model_name='researchsection',
            name='sponsor_btn_uz',
            field=models.CharField(blank=True, max_length=128, verbose_name='Tugma matni (UZ)'),
        ),
        migrations.AlterField(
            model_name='researchsection',
            name='title_em_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sarlavha — rangli qism (EN)'),
        ),
        migrations.AlterField(
            model_name='researchsection',
            name='title_em_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sarlavha — rangli qism (RU)'),
        ),
        migrations.AlterField(
            model_name='researchsection',
            name='title_em_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sarlavha — rangli qism (UZ)'),
        ),
        migrations.AlterField(
            model_name='researchsection',
            name='why_items_en',
            field=models.TextField(blank=True, verbose_name='“Nima uchun” bandlari (EN)'),
        ),
        migrations.AlterField(
            model_name='researchsection',
            name='why_items_ru',
            field=models.TextField(blank=True, verbose_name='“Nima uchun” bandlari (RU)'),
        ),
        migrations.AlterField(
            model_name='researchsection',
            name='why_items_uz',
            field=models.TextField(blank=True, verbose_name='“Nima uchun” bandlari | bilan (UZ)'),
        ),
        migrations.AlterField(
            model_name='researchsection',
            name='why_title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='“Nima uchun” sarlavhasi (EN)'),
        ),
        migrations.AlterField(
            model_name='researchsection',
            name='why_title_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='“Nima uchun” sarlavhasi (RU)'),
        ),
        migrations.AlterField(
            model_name='researchsection',
            name='why_title_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='“Nima uchun” sarlavhasi (UZ)'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='icon',
            field=models.CharField(blank=True, max_length=16, verbose_name='Ikonka (emoji)'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Sahifa manzili (URL)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Sahifa manzili (URL)'),
        ),
    ]
