# Generated by Django 6.0.5 on 2026-08-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_alter_aiproduct_metric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproduct',
            name='audience_en',
            field=models.TextField(blank=True, verbose_name='Auditoriya (EN)'),
        ),
        migrations.AlterField(
            model_name='aiproduct',
            name='audience_ru',
            field=models.TextField(blank=True, verbose_name='Auditoriya (RU)'),
        ),
        migrations.AlterField(
            model_name='aiproduct',
            name='audience_uz',
            field=models.TextField(blank=True, verbose_name='Auditoriya (UZ)'),
        ),
        migrations.AlterField(
            model_name='aiproduct',
            name='overview_en',
            field=models.TextField(blank=True, verbose_name='Umumiy tavsif (EN)'),
        ),
        migrations.AlterField(
            model_name='aiproduct',
            name='overview_ru',
            field=models.TextField(blank=True, verbose_name='Umumiy tavsif (RU)'),
        ),
        migrations.AlterField(
            model_name='aiproduct',
            name='overview_uz',
            field=models.TextField(blank=True, verbose_name='Umumiy tavsif (UZ)'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='lead_en',
            field=models.TextField(blank=True, verbose_name='Kirish qismi (EN)'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='lead_ru',
            field=models.TextField(blank=True, verbose_name='Kirish qismi (RU)'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='lead_uz',
            field=models.TextField(blank=True, verbose_name='Kirish qismi (UZ)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='badge_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='Kichik yorliq (EN)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='badge_ru',
            field=models.CharField(blank=True, max_length=128, verbose_name='Kichik yorliq (RU)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='badge_uz',
            field=models.CharField(blank=True, max_length=128, verbose_name='Kichik yorliq (UZ)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='copyright_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mualliflik huquqi matni (EN)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='copyright_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mualliflik huquqi matni (RU)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='copyright_uz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mualliflik huquqi matni (UZ)'),
        ),
    ]
