# Generated by Django 6.0.5 on 2026-08-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_alter_aiproduct_audience_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='about_en',
            field=models.TextField(blank=True, verbose_name='Haqida (EN)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='about_ru',
            field=models.TextField(blank=True, verbose_name='Haqida (RU)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='about_uz',
            field=models.TextField(blank=True, verbose_name='Haqida (UZ)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education_en',
            field=models.TextField(blank=True, verbose_name='Ta’lim | bilan (EN)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education_ru',
            field=models.TextField(blank=True, verbose_name='Ta’lim | bilan (RU)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education_uz',
            field=models.TextField(blank=True, verbose_name='Ta’lim | bilan (UZ)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='focuses_en',
            field=models.TextField(blank=True, verbose_name='Yo’nalishlar | bilan (EN)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='focuses_ru',
            field=models.TextField(blank=True, verbose_name='Yo’nalishlar | bilan (RU)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='focuses_uz',
            field=models.TextField(blank=True, verbose_name='Yo’nalishlar | bilan (UZ)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages_en',
            field=models.TextField(blank=True, verbose_name='Tillar | bilan (EN)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages_ru',
            field=models.TextField(blank=True, verbose_name='Tillar | bilan (RU)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages_uz',
            field=models.TextField(blank=True, verbose_name='Tillar | bilan (UZ)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Sahifa manzili (URL)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='staff_kind',
            field=models.CharField(choices=[('doctor', 'Shifokor'), ('professor', 'Professor'), ('nurse', 'Hamshira')], default='doctor', max_length=16, verbose_name='Toifasi'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo_url',
            field=models.CharField(blank=True, max_length=512, verbose_name='Yoki foto yo‘li/URL'),
        ),
    ]
