# Generated by Django 5.2.16 on 2026-10-07 16:24

import cms.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_doctor_about_en_doctor_about_ru_doctor_about_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='resume',
            field=models.FileField(blank=True, help_text='PDF, DOC yoki DOCX, 5MB gacha.', null=True, upload_to=cms.utils.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), cms.utils.validate_resume_size], verbose_name='Rezyume (PDF/DOC)'),
        ),
    ]
